# Generated by Django 4.1.7 on 2023-04-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applciation', '0003_alter_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=255),
        ),
    ]
